### ISSUE TITLE
The 'disqus' comment provider was not found.

### ISSUE THREAD

**Issue by paul-wang** [wowchemy/starter-hugo-research-group#2]
when I enabled the comment in params.toml , I got the following error.  Does this template support comment? 

Start building sites …
ERROR 2021/04/30 21:39:14 The 'disqus' comment provider was not found.
```code
[comments]
# Comment provider:
#   "": Disabled
#   "disqus": Disqus (https://disqus.com)
#   "commento": Commento (https://commento.io)
    provider = "disqus"
[comments.disqus]
    shortname = "xxxx"  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)
```

**Comment by gcushen** [comment]
These issues are for bug reports and feature requests. For support, see https://github.com/gcushen/hugo-academic/blob/master/.github/support.md
